version: '3.3'
services:

    ## WALLET ##

    # Wallet Frontend
#    wallet-frontend:
#      container_name: wallet-frontend
#      image: wallet-frontend:latest
#      ports:
#        - 4203:4203

    # Wallet API
    wallet-api:
      container_name: wallet-api
      image: wallet-api:latest
      environment:
        - "SPRING_PROFILES_ACTIVE=local-docker"
      command:
        - run
      volumes:
        - IN2_DOME_DATA:/dome_issuer_backend/data-root
      ports:
        - 8083:8083

    # Wallet API
    rp-interface:
      container_name: wallet-rp-interface
      image: wallet-rp-interface:latest
      environment:
        - "SPRING_PROFILES_ACTIVE=local-docker"
      command:
        - run
      links:
        - local-mysql
      volumes:
        - IN2_DOME_DATA:/dome_issuer_backend/data-root
      ports:
        - 8084:8084
    # Orion Context Broker
    wallet-orion:
      container_name: wallet-orion
      image: fiware/orion:latest
      links:
        - wallet-mongo
      ports:
        - "1026:1026"
      command: -dbhost wallet-mongo

    # MongoDB
    wallet-mongo:
      container_name: wallet-mongo
      image: mongo:4.4
      command: --nojournal
      volumes:
        - IN2_DOME_ORION:/data/db
        - IN2_DOME_ORION_DBCONFIG:/data/configdb
        
    # MySQL
    local-mysql:
      container_name: local-mysql
      image: mysql:8.0
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: D83Wh$tb83D8
        MYSQL_DATABASE: domedb
        MYSQL_USER: in2admin
        MYSQL_PASSWORD: in2pass
      volumes:
        - ./init:/docker-entrypoint-initdb.d
        - IN2_DOME_MYSQL:/var/lib/mysql
      ports:
        - 3309:3306

volumes:
  IN2_DOME_DATA:
  IN2_DOME_MYSQL:
  IN2_DOME_ORION:
  IN2_DOME_ORION_DBCONFIG:
  IN2_DOME_POSTGRES:
